version: "3.1"

services:
    mongodb:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PSWD}
            MONGO_INITDB_DATABASE: test
        # volumes:
        # - "${MONGODB_DATA_PATH}:/data/db"
        ports:
            - "${MONGODB_SERVER_PORT}:27017"
